on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: ./build/libs

    - name: Hash Artifacts 
      run: |
        for u in $(ls) 
        do
        echo "$(sha256sum $u)" >> hashes.sha256
        done
      shell: bash
      working-directory: ./build/libs
  
    - name: Upload Hashes
      uses: actions/upload-artifact@v2
      with:
        name: Hashes
        path: ./build/libs/hashes.sha256
